### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [tejas-ardeshna/TJTextField#2]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by tejas-ardeshna** [comment]
@lfarah It will done by this weekend.

**Comment by lfarah** [comment]
Thanks! 🎉

**Comment by tejas-ardeshna** [comment]
@lfarah TJTextField.Swift file available in Swift 3.0
